### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aadeabreu** [Airspace-Encounter-Models/em-pairing-geospatial#2]
Error while running RUN_1 and RUN2_geospatial_uncor. It seems I am having issues during the preallocation while setting the Canadian boundaries. Maybe I am missing a file from em-core. Do you know what the issue could be?

Error using geolinebuf>geoarcbuf (line 170)
Simulink model 'sph2cart' was called with incorrect number of arguments

Error in geolinebuf (line 67)
            [phib, lambdab] = geoarcbuf(lat(k), lon(k), lat(k+1), lon(k+1), ...

Error in bufferm>dobufferm (line 184)
        pc = geolinebuf(latClosed, lonClosed, bufwidth, n);

Error in bufferm (line 108)
[latb, lonb] = dobufferm(lat, lon, bufwidth, direction, npts - 1);

Error in IdentifyGeographicVariable>BufferBoundUnion (line 198)
    [latb_deg,lonb_deg] = bufferm(latIn_deg{i}(k),lonIn_deg{i}(k),p.Results.bufwidth_deg,'outPlusInterior');

Error in IdentifyGeographicVariable (line 77)
    [latCA_deg,lonCA_deg,~] = BufferBoundUnion(latCA_deg,lonCA_deg,p);

Error in createEncounters_2 (line 216)
        anchors.G = IdentifyGeographicVariable(anchors.lat_deg,anchors.lon_deg);

Error in RUN_2_geospatial_uncor (line 60)
    metadata = createEncounters_2(iiAnchors,outDir,... - Show complete stack trace

### Environment

- OS: [Windows 10]
- Programming language and version: [MATLAB 2020a]
- Are you running in a virtual machine" [no]

**Comment by aadeabreu** [comment]
@aweinert-MIT The issue I was having was caused by having run DEGAS' startup.m prior to running RUN_1.m. There might be a function that has the same name so RUN_1.m and RUN_2_geospatial_uncor.m were getting confused. 

Clearing the paths with `path(pathdef)` solved the issue. Alternatively, relaunching matlab also solves the issue.

**Comment by aweinert-MIT** [comment]
Your resolution is good and understandable. I typically don't run DEGAS and the encounter models in the same MATLAB instance and I think this is why I couldn't replicate the issue.

What was your DEGAS startup? Was it just `degas-core` or did it include more to the path?

**Comment by aadeabreu** [comment]
It also included `degas-pilotmodel` and `degas-daidalus`. The issue specifically is that `IdentifyGeographicVariable` calls 
[Matlab's sph2cart.m](https://www.mathworks.com/help/matlab/ref/sph2cart.html) but it was instead calling [DEGAS sph2cart.slx](https://github.com/mit-ll/degas-core/tree/main/code/block_libraries/basic_libraries/signalsLib/CoordinateTransformations/sph2cart). Interestingly, it only happens _**if**_ a simulink model that uses` sph2cart.slx` is open. I tried replicating the error by opening a clean matlab session -> running degas' `startup.m` -> running `startup_pairing_geo.m` -> and finally `RUN_2_geospatial_uncor.m` but the error did not occur in that case. I thought that was an interesting fyi.
