### ISSUE TITLE
[QUESTION] PLOT_1.m

### ISSUE THREAD

**Issue by aadeabreu** [Airspace-Encounter-Models/em-pairing-geospatial#3]
@aweinert-MIT Did you mean to delete `PLOT_1.m`  in v2.0.0? Old file still works with the new changes

**Comment by aweinert-MIT** [comment]
It was intentionally deleted as I was reworking to functionalize it and reintroduce it in a future reelease. I didn't think it was being used by anyone. Do you need it back?

**Comment by aadeabreu** [comment]
Understood. I don't really need it. If I ever need it, I can use a copy of the old file
